version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Budapest
    volumes:
      - ./config:/config
      - ./downloads:/downloads
      - ./watch:/watch
    ports:
      - 80:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped